version: '3'
services:
  webui:
    build: .
    image: knot/webui
    container_name: webui
    depends_on:
      - 'database'
    environment:
      - DEBUG=*
      - NODE_ENV=development
    security_opt:
      - seccomp=unconfined
    tmpfs:
      - /run
      - /run/lock
    ports:
      - '8080:8080'
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - .:/usr/local/bin/knot-web-app
      - /usr/local/bin/knot-web-app/node_modules
      - /usr/local/bin/knot-web-app/www
      - /var/run/docker.sock:/var/run/docker.sock:ro
  fog:
    build: ./docker/knot-cloud
    depends_on:
      - 'database'
    environment:
      - DB_NAME=knot_fog
    expose:
      - '3000'
  cloud:
    build: ./docker/knot-cloud
    depends_on:
      - 'database'
    expose:
      - '3000'
  database:
    image: mongo
    expose:
      - '27017'
