version: '2'
services:
  webui:
    build: .
    image: knot/webui
    container_name: webui
    environment:
      - NODE_ENV=dev
    security_opt:
      - seccomp=unconfined
    tmpfs:
      - /run
      - /run/lock
    ports:
      - '8080:8080'
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - .:/usr/local/bin/knot-web-app
      - /usr/local/bin/knot-web-app/node_modules
      - /usr/local/bin/knot-web-app/www
